profiles:
  default_profile:
    label: "Minecraft (OBS)"

    adapters:
      capture:
        name: "obsadapter"
        overrides:
          default_scene: "MC_Gameplay"
          default_profile: "MC_1080p60"
          enforce_mc_foreground: true
          record_dir: "C:/Users/USUARIO/Videos"

          auto_launch_obs: true
          obs_launch_wait_sec: 15.0
          
          capture_desktop_audio: true
          capture_mic_audio: false 

        preflights:
          - id: "capture.obs_launch"
            required: true

          - id: "capture.disk_space"
            required: true
            params:
              min_gb: 10
              path_key: "record_dir"

          - id: "capture.obs_health"
            required: true

          - id: "capture.window_foreground"
            required: false
            params:
              window_title_contains: "Minecraft"
      watcher:
        name: "replaywatcheradapter"
        overrides:
          watch_path: "C:/Users/USUARIO/Videos"

    pipelines:
      on_replay_detected: "ig_ready"
      on_capture_stopped: "handoff"

    hooks:
      notify:
        capture_started: true
        capture_stopped: true
      watcher:
        start_on_capture_started: true
